name: Build and Push Docker Image to Seven Bridges

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Seven Bridges Registry
        uses: docker/login-action@v3
        with:
          registry: images.sbgenomics.com
          username: ${{ secrets.SBG_USERNAME }}
          password: ${{ secrets.SBG_AUTH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t images.sbgenomics.com/ts-sandbox/rna-seq_recount3_versions:latest .

      - name: Push Docker image
        run: |
          docker push images.sbgenomics.com/ts-sandbox/rna-seq_recount3_versions:latest
